
api:
  container_name: ecommerce2
  image:  secret06/ecommercebuild:0.1
  command : pm2 start app.js --no-daemon --watch -i max --max-memory-restart 3G --merge-logs --log-date-format="YYYY-MM-DD HH:mm Z"
  restart: always
  ports:
    - "8085:8085"

  links:
      - mongodbs

mongodbs:
  container_name: mongodbecommerce2
  restart: always
  volumes:
    - /var/test:/data/db
  image: mongo:3.2
  ports:
    - "27017:27017"
