nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./api_courier
    ports:
        - "8084"
node2:
    build: ./api_courier
    ports:
        - "8084"
node3:
    build: ./api_courier
    ports:
        - "8084"