global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name:       'node-exporter'

    scrape_interval: 5s

    static_configs:
      - targets: ['192.168.90.71:9100']
        labels:
          group: 'production'

