haproxy:
    container_name: haproxy
    image: haproxy:1.7-alpine
    restart: always
    ports:
        - "80:80"
    volumes:
        - /run/haproxy/:/run/haproxy:rw
        - ./config:/usr/local/etc/haproxy:rw
        - /var/lib/haproxy:/var/lib/haproxy
    


