website_data:
  container_name: website_data
  image: website:2.0

ralali_nginx:
  container_name: nginx
  image: nginx:2.0
  ports:
    - "8000:8000"
  volumes_from:
    - website_data
  links:
    - ralali_hhvm_build

ralali_hhvm_build:
  container_name: hhvm
  image: hhvm:2.0
  command: hhvm --mode server --config /etc/hhvm/hhvm.ini
  volumes_from:
      - website_data


